name: Build all packages and dependencies
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Does this work?
        run: |
          echo ${{ inputs.python-version }}