name: Build all packages and dependencies
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string

jobs:
  build:
    name: Build all packages and dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-${{ inputs.poetry-version }}

      - name: Install Poetry ${{ inputs.poetry-version }}
        uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
        if: steps.cached-poetry.outputs.cache-hit != 'true'


      - name: Where is poetry installed?
        run: |
          which poetry
          poetry --version

      - name: Load cached venv
        uses: actions/cache@v4
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with test
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: What's in local?
        run: |
          ls -alR ~/.local


      - name: Install library
        run: poetry install --no-interaction
