name: Build all packages and dependencies
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string
      project-version:
        required: true
        type: string
    outputs:
      dist-cache-key:
        description: Cache key for build artifacts
        value: ${{ jobs.build.outputs.dist-cache-key }}

jobs:
  build:
    name: Build all packages and dependencies
    runs-on: ubuntu-latest
    outputs:
      dist-cache-key: ${{ steps.set-dist-cache-key.outputs.dist-cache-key }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Define cache keys for other jobs
        id: set-dist-cache-key
        run: |
          echo "dist-cache-key=dist-python3-${{ runner.os }}-v${{ inputs.project-version }}" >> $GITHUB_OUTPUT

      - name: Set up python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Initialize Poetry cache
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry${{ inputs.poetry-version }}-python${{ inputs.python-version }}-v${{ inputs.project-version }}-${{ runner.os }}-build

      - name: Install Poetry ${{ inputs.poetry-version }}
        uses: snok/install-poetry@v1
        if: steps.cached-poetry.outputs.cache-hit != true
        with:
          version: ${{ inputs.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Create distribution cache
        id: cached-distribution
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ steps.set-dist-cache-key.outputs.dist-cache-key }}

      - name: Build a wheel from the source
        run: poetry build --no-interaction
