---
name: CI

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  linting:
    uses: ./.github/workflows/linting.yml
    needs:
      - setup
    with:
      python-version: ${{ needs.setup.outputs.dev-python-version }}

  build:
    uses: ./.github/workflows/build.yml
    needs:
      - setup
      - linting
    with:
      poetry-version: ${{ needs.setup.outputs.poetry-version }}
      python-version: ${{ needs.setup.outputs.dev-python-version }}
      project-version: ${{ needs.setup.outputs.project-version }}
      build-wheel-cache-key: ${{ needs.setup.outputs.build-wheel-cache-key }}

  deploy-testing:
    name: Upload wheel to TestPyPi
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
    environment:
      name: devtest
      url: https://test.pypi.org/p/restsession
    permissions:
      id-token: write
    steps:
      - name: Load distribution cache
        id: cached-distribution
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ needs.setup.outputs.build-wheel-cache-key }}

      - name: Verify the cache
        run: |
          ls -la dist

      - name: Upload wheel to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    needs:
      - setup
      - build
      - deploy-testing
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ matrix.python-version }}
      poetry-version: ${{ needs.setup.outputs.poetry-version }}
      project-name: ${{ needs.setup.outputs.project-name }}
      project-version: ${{ needs.setup.outputs.project-version }}
