---
name: CI

on:
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  linting:
    uses: ./.github/workflows/linting.yml
    needs:
      - setup
    with:
      python-version: ${{ needs.setup.outputs.dev-python-version }}

  build:
    uses: ./.github/workflows/build.yml
    needs:
      - setup
      - linting
    with:
      poetry-version: ${{ needs.setup.outputs.poetry-version }}
      python-version: ${{ needs.setup.outputs.dev-python-version }}

  deploy-testing:
    name: Upload wheel to TestPyPi
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
    environment:
      name: devtest
      url: https://test.pypi.org/p/restsession
    permissions:
      id-token: write
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: build-python3-${{ runner.os }}
          path: dist

      - name: Did we get the proper version
        run: |
          echo ${{ needs.setup.outputs.project-name }}
          echo ${{ needs.setup.outputs.project-version }}

      - name: Upload wheel to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  execute-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    needs:
      - setup
      - build
      - deploy-testing
    uses: ./.github/workflows/testing-entrypoint.yml
    with:
      python-version: ${{ matrix.python-version }}
      poetry-version: ${{ needs.setup.outputs.poetry-version }}
      build-wheel-name: ${{ needs.build.outputs.build-wheel-name }}

