name: Install Poetry and create the venv
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string
      poetry-cache-key:
        required: true
        type: string

jobs:
  build:
    name: Install Poetry
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ inputs.poetry-cache-key }}

      - name: Install Poetry ${{ inputs.poetry-version }}
        uses: snok/install-poetry@v1
        if: steps.cached-poetry.outputs.cache-hit != true
        with:
          version: ${{ inputs.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: false
