name: Python version-specific jobs
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string

jobs:
  test:
    name: Run tests for Python ${{ inputs.python-version }}
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ inputs.python-version }}
      cached-venv-key: ${{ needs.build.outputs.cached-venv-key }}
      build-wheel-name: ${{ needs.build.outputs.build-wheel-name }}
