name: Python version-specific jobs
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      cached-venv-key:
        required: true
        type: string
      build-wheel-name:
        required: true
        type: string

jobs:
  test:
    name: Run tests for Python ${{ inputs.python-version }}
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ inputs.python-version }}
      cached-venv-key: ${{ inputs.cached-venv-key }}
      build-wheel-name: ${{ inputs.build-wheel-name }}
