---
name: PyPi Release

on:
  pull_request_target:
    types:
      - closed
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  release-build:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build.yml
    needs:
      - setup
    with:
      poetry-version: ${{ needs.setup.outputs.poetry-version }}
      python-version: ${{ needs.setup.outputs.dev-python-version }}
      project-version: ${{ needs.setup.outputs.project-version }}
      build-wheel-cache-key: ${{ needs.setup.outputs.build-wheel-cache-key }}

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs:
      - setup
      - release-build
    environment:
      name: release
      url: https://pypi.org/p/restsession
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Load distribution cache
        id: cached-distribution
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ needs.setup.outputs.build-wheel-cache-key }}

      - name: Verify the cache
        run: |
          ls -la dist

      - name: Check version for RC status
        id: release-check
        run: |
          if [[ "${{ needs.setup.outputs.project-version }}" =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
            echo "pypi-release=true" >> $GITHUB_OUTPUT
          fi

      - name: Tag this commit
        id: create_tag
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          tag: ${{ needs.setup.outputs.project-version }}
          artifacts: "dist/*.whl,dist/*.tar.gz"

      - name: Upload wheel to PyPi Production
        if: >-
          ${{
            steps.release-check.outputs.pypi-release == 'true' && 
            needs.setup.outputs.local-version-higher == 'true'
          }}
        uses: pypa/gh-action-pypi-publish@release/v1
