name: Test supported Python versions
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string
      project-name:
        required: true
        type: string
      project-version:
        required: true
        type: string

jobs:
  install-poetry:
    name: Install Poetry
    uses: ./.github/workflows/install-poetry.yml
    with:
      python-version: ${{ inputs.python-version }}
      poetry-version: ${{ inputs.poetry-version }}


  #  testing-env:
#    name: Build the version-specific testing environment
#    uses: ./.github/workflows/create-test-env.yml
#    with:
#      python-version: ${{ inputs.python-version }}
#      poetry-version: ${{ inputs.poetry-version }}

  test:
    name: Run tests for Python ${{ inputs.python-version }}
    needs:
      - install-poetry
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ inputs.python-version }}
      poetry-cache-key: ${{ needs.install-poetry.outputs.poetry-cache-key }}
      project-name: ${{ inputs.project-name }}
      project-version: ${{ inputs.project-version }}
