name: Test supported Python versions
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string
      project-name:
        required: true
        type: string
      project-version:
        required: true
        type: string

jobs:
  test:
    name: Run tests for Python ${{ inputs.python-version }}
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ inputs.python-version }}
      poetry-version: ${{ inputs.poetry-version }}
      project-name: ${{ inputs.project-name }}
      project-version: ${{ inputs.project-version }}
